### ISSUE TITLE
I modified your code to train my crack data set and encountered some problems

### ISSUE THREAD

**Issue by wanjianr** [arnab39/Semi-supervised-segmentation-cycleGAN#11]
My dataset n_channel = 2 (cracks or cracks), I like your code training cityscapes in the code, change the n_channels to 2, but the program is running to The Times wrong one_hot tensor input to the model (pictured), I find a solution, the Internet has a cudnn version of the problem, but I can run successful your source code, so I hope to get your help, thank you!
![problem](https://user-images.githubusercontent.com/53571760/64859468-e80cd080-d65c-11e9-914b-9080beed3054.png)

**Comment by aniket-agarwal1999** [comment]
Hi @wanjianr I am not able to clearly get the problem you are facing, maybe you can elucidate a bit more. If it related to the wrong number of channels problem, you may once see the `make_one_hot` function in `utils.py`.

**Comment by aniket-agarwal1999** [comment]
Closing it for now
