### ISSUE TITLE
 Why does 'Sample_from_Pool' work?

### ISSUE THREAD

**Issue by daifeng2016** [arnab39/Semi-supervised-segmentation-cycleGAN#15]
Hi, 
 In your project, during the training of D,  'Sample_from_Pool' is used. What is the  difference of training D without 'Sample_from_Pool'?  Could you give some explaintions？

**Comment by aniket-agarwal1999** [comment]
Hi @daifeng2016 , this is a technique that has been used in the original cycleGAN paper for stability reasons. You can check out the paper that introduced the technique for proper explanation for the same.
